services:
  solana-validator:
    image: solanalabs/solana:v1.18.23
    container_name: solana-validator
    ports:
      - "8899:8899"
      - "8900:8900"
    restart: always
    volumes:
      - solana-data:/var/lib/solana
volumes:
  solana-data:

    